default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: Aa@123456
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: rabbit

test:
  <<: *default
  database: rabbit

production:
  <<: *default
  database: rabbit